version: "3.8"
services:
  passwordsafe3:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    volumes:
      - ../frontend:/app
  passwordsafe-api3:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - 5002:5001
    volumes:
      - ../backend:/backend
